gha-runner-scale-set:

  githubConfigUrl: https://github.com/ascend-gha-runners

  githubConfigSecret: ascend-runner-mgmt-secret

  listenerTemplate:
    spec:
      containers:
        - name: listener
          image: 
      nodeSelector:
        beta.kubernetes.io/arch: amd64

  containerMode:
    type: "kubernetes-novolume"

  template:
    spec:
      serviceAccountName: runner-service-account
      schedulerName: volcano
      nodeSelector:
        kubernetes.io/arch: arm64
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret-model-gy
      containers:
        - name: runner
          image: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/runner-containers-hooks:release-no_volumes-9c3ea5
          command: ["/home/runner/run.sh"]
          securityContext:
            capabilities:
              add:
                - SYS_RESOURCE
          env:
            - name: ACTIONS_RUNNER_CONTAINER_HOOKS
              value: /home/runner/k8s/index.js
            - name: NODE_OPTIONS
              value: "--dns-result-order=ipv4first"
            - name: ACTIONS_RUNNER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
              value: "false"
            - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
              value: /home/runner/pod-templates/default.yaml
            - name: ACTIONS_RUNNER_USE_KUBE_SCHEDULER
              value: "false"
            - name: ACTIONS_RUNNER_PREPARE_JOB_TIMEOUT_SECONDS
              value: "3600"
            - name: ACTIONS_RUNNER_IMAGE
              value: swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/runner-containers-hooks:release-no_volumes-9c3ea5
            - name: ACTIONS_RUNNER_KUBERNETES_NAMESPACE
              value: ascend-gha-runners
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: pod-templates
              mountPath: /home/runner/pod-templates
              readOnly: true
            - name: shared-volume
              mountPath: /root/.cache
      volumes:
        - name: work
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteMany"]
                storageClassName: "sfsturbo-subpath-sc"
                resources:
                  requests:
                    storage: 64Gi
        - name: pod-templates
          configMap:
            name: pod-template-npu-1
        - name: shared-volume
          persistentVolumeClaim:
            claimName: ascend-ci-share
        - name: custom-index
          persistentVolumeClaim:
            claimName: custom-index
        - name: app-data
          emptyDir: {}
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-gha-rs-controller

  listenerMetrics:
    counters:
      gha_started_jobs_total:
        labels:
          ["repository", "organization", "enterprise", "job_name", "event_name", "job_workflow_ref"]
      gha_completed_jobs_total:
        labels:
          [
            "repository",
            "organization",
            "enterprise",
            "job_name",
            "event_name",
            "job_result",
            "job_workflow_ref",
          ]
    gauges:
      gha_assigned_jobs:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
      gha_running_jobs:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
      gha_registered_runners:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
      gha_busy_runners:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
      gha_min_runners:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
      gha_max_runners:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
      gha_desired_runners:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
      gha_idle_runners:
        labels: ["name", "namespace", "repository", "organization", "enterprise"]
    histograms:
      gha_job_startup_duration_seconds:
        labels:
          ["repository", "organization", "enterprise", "job_name", "event_name","job_workflow_ref"]
        buckets:
          [
            0.01,
            0.05,
            0.1,
            0.5,
            1.0,
            2.0,
            3.0,
            4.0,
            5.0,
            6.0,
            7.0,
            8.0,
            9.0,
            10.0,
            12.0,
            15.0,
            18.0,
            20.0,
            25.0,
            30.0,
            40.0,
            50.0,
            60.0,
            70.0,
            80.0,
            90.0,
            100.0,
            110.0,
            120.0,
            150.0,
            180.0,
            210.0,
            240.0,
            300.0,
            360.0,
            420.0,
            480.0,
            540.0,
            600.0,
            900.0,
            1200.0,
            1800.0,
            2400.0,
            3000.0,
            3600.0,
          ]
      gha_job_execution_duration_seconds:
        labels:
          [
            "repository",
            "organization",
            "enterprise",
            "job_name",
            "event_name",
            "job_result",
            "job_workflow_ref"
          ]
        buckets:
          [
            0.01,
            0.05,
            0.1,
            0.5,
            1.0,
            2.0,
            3.0,
            4.0,
            5.0,
            6.0,
            7.0,
            8.0,
            9.0,
            10.0,
            12.0,
            15.0,
            18.0,
            20.0,
            25.0,
            30.0,
            40.0,
            50.0,
            60.0,
            70.0,
            80.0,
            90.0,
            100.0,
            110.0,
            120.0,
            150.0,
            180.0,
            210.0,
            240.0,
            300.0,
            360.0,
            420.0,
            480.0,
            540.0,
            600.0,
            900.0,
            1200.0,
            1800.0,
            2400.0,
            3000.0,
            3600.0,
          ]

